SELECT 
  USER_NAME,
  COUNT(*) AS query_count,
  AVG(CREDITS_USED) AS avg_credits_used
FROM 
  INFORMATION_SCHEMA.QUERY_HISTORY
WHERE 
  START_TIME > DATEADD(DAY, -7, CURRENT_TIMESTAMP())
GROUP BY 
  USER_NAME
ORDER BY 
  avg_credits_used DESC
LIMIT 10;
